version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - errcheck
      - text: "Error return value of .*(Close|close).*is not checked"
        linters:
          - errcheck
      - text: "Error return value of `os\\.(Setenv|Unsetenv)`"
        linters:
          - errcheck
      - text: "Error return value of `\\(\\*encoding/json"
        linters:
          - errcheck
